### ISSUE TITLE
re-model

### ISSUE THREAD

**Issue by ashbeekim** [PreOnboarding-Team-C/Madup#8]
* drop
    * [x] Ads.uid
    * [x] ClientPlatform
    * [x] Ads.$계산해야 하는 값: ctr, roas, cpc, cvr, cpa
* add & edit
    * [x] Client.client_name > Client.client_number
    * [x] Client.다른 기입 가능할 법한 고객 정보
* redefine
    * [x] field-type
    * [x] parameters

Assignee: @do-not-do-that 
Reviewer: @Bruno-Jang , @castela0119 , @AshbeeKim

**Comment by Bruno-Jang** [comment]
FK로 연결되는 컬럼에는 자동으로 _id가 붙는 점 참고 부탁드립니다.

**Comment by ashbeekim** [comment]
* cost: 999 ~ 999999
* impression: 99 ~ 999999
* click: 9 ~ 9999
* conversion: 9 ~ 9999
* cv: 9 ~ 99999999
자세한 필드 변환  요청은 commit no. f899957675d92bcf975acb34a9a4b9b82724ca14 에 작성했습니다~
